# Generated by Django 3.1.7 on 2022-07-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('wday', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TEmployees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=100)),
            ],
        ),
    ]
